### PR TITLE
Add portuguese version of the content

### PR DESCRIPTION
**Pull request by nazarepiedady**
Hi, I hope you are okay.
In this pull request, I am adding the Portuguese version of the content to the website.
It was a delightful experience, so congratulations friends.

### CODE REVIEW

**Comment by nazarepiedady** [comment]
@Heydon, @iheni, @IanPouncey, @LJWatson, @hidde, @notabene, @hanshillen, @stevefaulkner, @MakotoUeki, @patrickhlauke, @partisiber, @chaals.

**Comment by LJWatson** [comment]
Thank you @nazarepiedady. We'll review this and hopefully merge it soon.

**Comment by nazarepiedady** [comment]
@LJWatson, thanks, I will be available to do all updates needed.

**Review by LJWatson — APPROVED** [review]

**Comment by LJWatson** [comment]
Thank you @nazarepiedady. We've merged your translation now 😁 

If you use Mastodon or Linkedin and would be OK to share your details, we'll mention you when we post about this new translation.

Thank you again.

**Comment by nazarepiedady** [comment]
@LJWatson, I use LinkedIn, and here is my LinkedIn address: https://linkedin.com/in/nazarepiedady

**Pull request merged**
